backend = "glx";
use-damage = true;
vsync = true;

rules = (
    {
        opacity = 1.0;
    },
    {
        match = "!focused";
        opacity = 0.85;
        dim = 0.05;
    },
    {
        match = "window_type = 'dock' || window_type = 'desktop'";
        corner-radius = 0;
        shadow = false;
    },
    {
        match = "className = 'fcitx'";
        fade = false;
    },
    {
        match = "name = 'Notification' || class_g = 'Conky' || class_g ?= 'Notify-osd' || class_g = 'Cairo-clock' || _GTK_FRAME_EXTENTS@:c";
        shadow = false;
    },
    {
        match = "(class_g = 'Firefox' && argb) || class_g = 'Vlc' || class_g = 'Gimp' || class_g = 'mpv' || name *? = 'GeckoChildProcess' || class_g = 'zen-alpha' || class_g = 'zen'";
        opacity = 1.0;
    },
    {
        match = "window_type = 'tooltip'";
        fade = true;
        shadow = true;
        opacity = 0.75;
        focus = true;
        full-shadow = false;
    },
    {
        match = "window_type = 'popup_menu' || window_type = 'dropdown_menu'";
        opacity = 0.95;
    }
);

corner-radius = 4;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 6;

shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.6;

blur-method = "none";
blur-background = false;
