# font_family      family="ProggySmallTT"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size 9.0
include ~/.cache/wal/colors-kitty.conf
 confirm_os_window_close 0 
background_opacity 0.8

shell fish

# BEGIN_KITTY_FONTS
font_family      family="Terminus (TTF)"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
